variables:
  SCHEDULER_PARAMETERS: "-n 1 -p nitrogen"
  USER: legit


stages:
    - build
    - test
    - cleanup

before_script:
        - hostname

####################
### BUILD IMAGES ###
####################

build-docker-test-image:
    tags:
       - local
       - shell
    stage: build
    script:
       - docker build --no-cache -t vib2d .

#################
### UNITTESTS ###
#################

unittest-Calc2dir:
    tags:
        - local
        - shell
    stage: test
    needs: [build-docker-test-image]
    script:
        - docker run --workdir /app/src/Vibrations2D/test vib2d pytest -v test_Calc2dir.py

unittest-ExcitonModel:
    tags:
        - local
        - shell
    stage: test
    needs: [build-docker-test-image]
    script:
        - docker run --workdir /app/src/Vibrations2D/test vib2d pytest -v test_ExcitonModel.py

unittest-FrequencyDomain:
    tags:
        - local
        - shell
    stage: test
    needs: [build-docker-test-image]
    script:
        - docker run --workdir /app/src/Vibrations2D/test vib2d pytest -v test_FrequencyDomain.py

unittest-spectra:
    tags:
        - local
        - shell
    stage: test
    needs: [build-docker-test-image]
    script:
        - docker run --workdir /app/src/Vibrations2D/test vib2d pytest -v test_spectra.py

unittest-TimeDomain:
    tags:
        - local
        - shell
    stage: test
    needs: [build-docker-test-image]
    script:
        - docker run --workdir /app/src/Vibrations2D/test vib2d pytest -v test_TimeDomain.py

##################
#### CLEAN UP ####
##################

cleanup-docker:
    stage: cleanup
    tags: [local, shell]
    needs:
        - build-docker-test-image
        - unittest-Calc2dir
        - unittest-ExcitonModel
        - unittest-FrequencyDomain
        - unittest-spectra
        - unittest-TimeDomain
    script:
        - docker rm $(docker ps --filter status=exited -q)
        - docker rmi -f vib2d:latest
        - docker system df
    when: always
