variables:
  SCHEDULER_PARAMETERS: "-n 1 -p nitrogen"
  USER: legit

stages:
    - build
    - test
    - autodoc
    - deploy
    - cleanup

before_script:
        - hostname

####################
### BUILD IMAGES ###
####################

### PIP ###
build-docker-test-image:
    tags:
       - local
       - shell
    stage: build
    script:
       - docker build --no-cache -t vib2d:$CI_PIPELINE_ID .

### CONDA ###
build-docker-conda-test-image:
    tags:
       - local
       - shell
    stage: build
    script:
       - docker build --no-cache -t vib2dconda:$CI_PIPELINE_ID -f Dockerfile.Conda . 

#################
### UNITTESTS ###
#################

unittest-Calc2dir:
    tags:
        - local
        - shell
    stage: test
    needs: [build-docker-test-image]
    script:
        - docker run --workdir /app/src/Vibrations2D/test vib2d:$CI_PIPELINE_ID pytest -v test_Calc2dir.py

unittest-ExcitonModel:
    tags:
        - local
        - shell
    stage: test
    needs: [build-docker-test-image,unittest-Calc2dir]
    script:
        - docker run --workdir /app/src/Vibrations2D/test vib2d:$CI_PIPELINE_ID pytest -v test_ExcitonModel.py

unittest-FrequencyDomain:
    tags:
        - local
        - shell
    stage: test
    needs: [build-docker-test-image,unittest-Calc2dir]
    script:
        - docker run --workdir /app/src/Vibrations2D/test vib2d:$CI_PIPELINE_ID pytest -v test_FrequencyDomain.py

unittest-spectra:
    tags:
        - local
        - shell
    stage: test
    needs: [build-docker-test-image,unittest-Calc2dir]
    script:
        - docker run --workdir /app/src/Vibrations2D/test vib2d:$CI_PIPELINE_ID pytest -v test_spectra.py

unittest-TimeDomain:
    tags:
        - local
        - shell
    stage: test
    needs: [build-docker-test-image,unittest-Calc2dir]
    script:
        - docker run --workdir /app/src/Vibrations2D/test vib2d:$CI_PIPELINE_ID pytest -v test_TimeDomain.py

unittest-all-Conda:
    tags:
        - local
        - shell
    stage: test
    needs: [build-docker-conda-test-image]
    script:
        - docker run --workdir /app/src/Vibrations2D/test vib2dconda:$CI_PIPELINE_ID conda run -n Vib2DCondaENV pytest -v


#######################
#### DOCUMENTATION ####
#######################

build-docker-sphinx-autodoc-image:
    tags:
       - local
       - shell
    stage: build
    script:
       - docker build -t vib2d_sphinxdoc:$CI_PIPELINE_ID -f doc/Dockerfile .

build-sphinx-doc:
    tags:
        - local
        - shell
    stage: autodoc
    needs: [build-docker-sphinx-autodoc-image]
    script:
        - docker run --workdir /app/doc --name vib2d_sphinxdoc_cont vib2d_sphinxdoc:$CI_PIPELINE_ID sphinx-build source build


pages:
    tags:
        - local
        - shell
    stage: deploy
    needs: [build-sphinx-doc]
    script:
        - docker cp vib2d_sphinxdoc_cont:/app/doc/build/. public/
    artifacts:
        paths:
         - public

##################
#### CLEAN UP ####
##################

cleanup-docker:
    stage: cleanup
    tags: [local, shell]
    needs:
        - build-docker-test-image
        - build-docker-conda-test-image
        - unittest-Calc2dir
        - unittest-ExcitonModel
        - unittest-FrequencyDomain
        - unittest-spectra
        - unittest-TimeDomain
        - unittest-all-Conda
        - build-docker-sphinx-autodoc-image
        - build-sphinx-doc
    script:
        - docker rm $(docker ps --filter status=exited -q)
        - docker rmi -f vib2d:$CI_PIPELINE_ID
        - docker rmi -f vib2dconda:$CI_PIPELINE_ID
        - docker rmi -f vib2d_sphinxdoc:$CI_PIPELINE_ID
        - docker system df
    when: always
